journal_title: "my journal"
journal_description: "thoughts and happenings"

upload_folder: 'uploads'
optimized_folder: 'uploads/optimized'
max_content_length: 300000000
posts_per_page: 15
optimized_width: 1200 # optimized images will be x pixels wide

# mastodon configuration
mastodon:
  instance_url: ""  # e.g., "https://mastodon.social"
  access_token: ""  # your mastodon access token
  privacy: "private"  # default privacy level: public, unlisted, private, direct