journal_title: "my journal"
journal_description: "thoughts and happenings"

upload_folder: 'uploads'
optimized_folder: 'uploads/optimized'
max_content_length: 300000000
posts_per_page: 15
optimized_width: 1200 # optimized images will be x pixels wide
webring_small_folder: 'uploads/webring_small'
webring_tiny_folder: 'uploads/webring_tiny'
webring_small_width: 960
webring_tiny_width: 256
images_per_page: 30

# mastodon configuration
mastodon:
  instance_url: ""  # e.g., "https://mastodon.social"
  access_token: ""  # your mastodon access token
  privacy: "private"  # default privacy level: public, unlisted, private, direct